[devices]
master_node = { name = "master_mix", nice_name = "Master" }
stream_node = { name = "stream_mix", nice_name = "Stream" }

in_nodes = [
    { name = "mic_sink", nice_name = "  Mic  " }
]

out_nodes = [
    { name = "default_sink", nice_name  = "Default"},
    { name = "game_sink", nice_name     = " Game "},
    { name = "comms_sink", nice_name    = " Comms "},
    { name = "media_sink", nice_name    = " Media "},
    { name = "aux_sink", nice_name      = "  Aux  "}
]

# [apps]
# firefox = ""


# [naming]
# mix_main = "Master"
# mix_stream = "Stream"

# out_mix

[theme]
window_background_color = "#171717"
group_background_color = "#171717"
mixer_background_color = "#171717"

group_font_color = "#FFFFFF"
group_font_size = 14
group_font_name = ""

mixer_font_color = "#FFFFFF"
mixer_font_size = 14
mixer_font_name = ""

other_font_color = "#FFFFFF"
other_font_size = 14
other_font_name = ""